domain: http://localhost

server:
  port: 8762

spring:
  application:
    name: discovery-service

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${domain}:8761/eureka
    instance:
      preferIpAddress: true
      instanceId: ${spring.application.name}:${random.value}
      hostname: ${domain}

logging:
  level:
    com:
      netflix:
        eureka: INFO
        discovery: OFF
