server:
  port: 9080

spring:
  application:
    name: gateway-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    metadata-map:
      configPath: ${server.servlet.context-path}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}

springdoc:
  packagesToScan: br.com.example.spring.cloud.gateway.eureka.sample.controller
  pathsToMatch: /**

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE