server:
  port: 9080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: orderId
          uri: lb://order-service
          predicates:
            - Path=/api/v1/orders

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE