server:
  port: 9081

spring:
  application:
    name: product-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
  instance:
    metadata-map:
      configPath: ${server.servlet.context-path}
    preferIpAddress: true
    instanceId: ${spring.application.name}:${random.value}

springdoc:
  packagesToScan: br.com.example.spring.cloud.eureka.product.sample.controller
  pathsToMatch: /**