server:
  port: 9080
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    metadata-map:
      configPath: ${server.servlet.context-path}
    preferIpAddress: true

springdoc:
  packagesToScan: br.com.example.spring.cloud.eureka.order.sample.controller
  pathsToMatch: /**